Repository whatever-mentoring/AKKIN_iOS, pull requests merged in 2024-01, with the labels that each got.

#71 [fix] 메인화면에 변경사항 발생시 API 재호출 및 뷰 reload
  AKKIN/AKKIN.xcodeproj/project.pbxproj
  AKKIN/AKKIN/Presentation/Main/MainCardCollectionView.swift
  AKKIN/AKKIN/Presentation/Main/MainGalleryCollectionView.swift
  AKKIN/AKKIN/Presentation/Main/MainView.swift
  AKKIN/AKKIN/Presentation/Main/MainViewController.swift
Labels: fix ⚒️, 지윤 🐣

#77 [Feat] 카카오톡 공유하기 추가
  AKKIN/AKKIN.xcodeproj/project.pbxproj
  AKKIN/AKKIN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AKKIN/AKKIN/App/AppDelegate.swift
  AKKIN/AKKIN/Presentation/CardSave/CardSavePageView.swift
  AKKIN/AKKIN/Presentation/CardSave/CardSaveViewController.swift
  AKKIN/AKKIN/Support/Info.plist
Labels: feat 💜, 종원 🧸

#79 [Fix] 카카오톡 공유하기 오류 수정
  AKKIN/AKKIN/App/SceneDelegate.swift
  AKKIN/AKKIN/Presentation/CardSave/CardSaveViewController.swift
Labels: fix ⚒️, 종원 🧸

#81 [Fix] AppDelegate Kakao Key 수정
  AKKIN/AKKIN/App/AppDelegate.swift
Labels: fix ⚒️, 종원 🧸

#83 add: 카카오톡 공유하기 템플릿 내용 추가
  AKKIN/AKKIN/Presentation/CardSave/CardSaveViewController.swift
Labels: add➕, 종원 🧸
